<?php
$listeOeuvres = [
    [
        "id" => 1,
        "img" => "clark-van-der-beken.png",
        "alt" => "Dodomu",
        "titre" => "DODOMU",
        "auteur" => "Mia Tozerski",
        "description" => "Mia Tozerski est une artiste peintre ukrainienne réfugiée de la guerre. Sur cette œuvre, Dodomu (\"domicile\" en ukrainien), elle nous montre la tristesse du peuple ukrainien qu'elle partage, ayant elle-même dû quitter son foyer. L'œuvre évoque le drapeau liquéfié d'une Ukraine en souffrance, pleurant la mort de ses compatriotes. Ce travail chargé d'émotion est le symbole d'un événement qui marquera l'Histoire. Cette peinture à l'acrylique rayonne grâce à son fond lisse et ses mélanges de couleurs éclatantes.",
    ],
    [
        "id" => 2,
        "img" => "pawel-czerwinski-3.png",
        "alt" => "Aashaaheen Baadal",
        "titre" => "AASHAAHEEN BAADAL",
        "auteur" => "Anaisha Devi",
        "description" => "Sur cette oeuvre conceptuelle à la fois organique, minérale et liquide, Anaisha Devi nous transporte dans un nuage noir envoûtant. Un sombre tableau qui, par son verni éclatant, rayonne tel un marbre poli. Une oeuvre à la cohérence transcendantale, exécutée à la perfection.",
    ],
    [
        "id" => 3,
        "img" => "dan-cristian-padure.png",
        "alt" => "Nightlife Traffic",
        "titre" => "NIGHTLIFE TRAFFIC",
        "auteur" => "Andrew Forsythe",
        "description" => "Andrew Forsythe, artiste des formes et des couleurs, nous entraîne dans un tourbillon hypnotique. 'Nightlife Traffic' est une exploration sensorielle immersive de la vie nocturne moderne, capturant l'essence pulsante et chaotique des métropoles nocturnes avec une intensité visuelle et émotionnelle qui invite à une réflexion profonde sur la dynamique urbaine contemporaine. Ses œuvres révèlent la beauté cachée des rues animées et des rencontres fortuites.",
    ],
    [
        "id" => 4,
        "img" => "steve-johnson-5.png",
        "alt" => "Le refuge de l'Havre",
        "titre" => "LE REFUGE DE L'HAVRE",
        "auteur" => "Simon Pelletier",
        "description" => "Simon Pelletier, explorateur des émotions par la couleur, nous transporte à travers un océan de calme et de plénitude. Les tons d'orange et de bleu évoquent un paisible coucher de soleil sur une mer calme. L'œuvre capture l'instant fugace où la mer et le ciel se fondent harmonieusement, offrant un moment de sérénité contemplative. Les teintes douces et vibrantes dansent ensemble sur la toile, invitant le spectateur à plonger dans une méditation tranquille, où le temps semble suspendu.",
    ],
    [
        "id" => 5,
        "img" => "steve-johnson.png",
        "alt" => "Red Washover",
        "titre" => "RED WASHOVER",
        "auteur" => "Kit Van Der Borght",
        "description" => "Kit Van Der Borght nous plonge ici dans un monde vibrant et exotique. Cette œuvre capture l'énergie des récifs coralliens d'une mer tropicale, où la vie marine foisonne dans une symphonie de couleurs. Chaque nuance danse ensemble, créant une harmonie audacieuse et envoûtante qui invite à explorer un paradis aquatique. Kit Van Der Borght célèbre la joie et la gaieté dans une symphonie d'émotions.",
    ],
    [
        "id" => 6,
        "img" => "pawel-czerwinski.png",
        "alt" => "Chromatics",
        "titre" => "CHROMATICS",
        "auteur" => "Jean-Michel Delatronchette",
        "description" => "'Chromatics' explore les profondeurs insondables de l'univers, révélant ses mystères et sa vastitude cosmique, où chaque coup de pinceau est une porte ouverte vers l'inconnu.",
    ],
    [
        "id" => 7,
        "img" => "jazmin-quaynor.png",
        "alt" => "Digital Negative",
        "titre" => "DIGITAL NEGATIVE",
        "auteur" => "Hamish McKee",
        "description" => "'Digital Negative' est une exploration audacieuse des interconnexions entre le réel et le virtuel, où les formes se dissolvent et se recomposent dans un ballet numérique. L'oeuvre nous transporte dans une méditation sur la fluidité de l'identité et de l'expression dans l'ère numérique.",
    ],
    [
        "id" => 8,
        "img" => "steve-johnson-6.png",
        "alt" => "Blast from the past",
        "titre" => "BLAST FROM THE PAST",
        "auteur" => "Juliette Baskerville",
        "description" => "Juliette Baskerville nous plonge dans un voyage temporel et émotionnel avec 'Blast from the Past'. Cette œuvre abstraite évoque des souvenirs enfouis et des échos du passé à travers des formes indéfinies et des éléments dynamiques.",
    ],
    [
        "id" => 9,
        "img" => "victor-grabarczyk.png",
        "alt" => "Hurricane",
        "titre" => "HURRICANE",
        "auteur" => "Natalie Wellington",
        "description" => "Natalie Wellington capture la puissance et le chaos d'une tempête intérieure. L'œuvre exprime la turbulence et l'énergie brute d'un ouragan, évoquant des émotions intenses et des forces incontrôlables. Les contrastes audacieux créent une sensation de désorientation et de force implacable, reflétant les conflits internes et les bouleversements personnels.'Hurricane' invite à contempler la nature tumultueuse de l'existence humaine et et la résilience face aux tempêtes de la vie.",
    ],
    [
        "id" => 10,
        "img" => "pawel-czerwinski-2.png",
        "alt" => "La marée rouge",
        "titre" => "LA MARÉE ROUGE",
        "auteur" => "Martin Rodriguez",
        "description" => "Martin Rodriguez, grand passionné des régions volcaniques, capture ici la puissance et fluidité de la lave volcanique en éruption, exprimant à la fois destruction et création. À travers des formes dynamiques et mouvantes, Rodriguez nous plonge dans un moment de pure énergie, où le chaos et la beauté se rencontrent.",
    ],
    [
        "id" => 11,
        "img" => "steve-johnson-2.png",
        "alt" => "Asimilacion",
        "titre" => "ASIMILACION",
        "auteur" => "Angel Sanchez-Fernandez",
        "description" => "Angel Sanchez-Fernandez s'est inspiré des régions du pôle nord dans ces journées où le ciel est gris. Les formes abstraites évoquent les paysages glacés et les vastes étendues arctiques. Les contrastes subtils entre les tons sombres et clairs créent une atmosphère de calme et de mystère. Cette composition invite le spectateur à contempler la beauté austère et la solitude paisible de l'Arctique, capturées avec une sensibilité artistique distinctive.",
    ],
    [
        "id" => 12,
        "img" => "fly-d.png",
        "alt" => "La Galaxia Gialla",
        "titre" => "LA GALAXIA GIALLA",
        "auteur" => "Eduardo Tancredi",
        "description" => " 'La Galaxia Gialla' captive par sa simplicité audacieuse. Ses légères tonalités de jaune se mêlent et s'étendent, créant une galaxie visuelle où les frontières entre les formes semblent se dissoudre. L'artiste fait référence ici à l'harmonie cosmique et à son énergie vibrante réussissant ainsi à transporter le spectateur dans une immersion sensorielle.",
    ],
    [
        "id" => 13,
        "img" => "orfeas-green.png",
        "alt" => "Puffy Amalgamate",
        "titre" => "PUFFY AMALGAMATE",
        "auteur" => "Sandro De Blasi",
        "description" => " L'oeuvre capture l'énergie dynamique des éléments en mouvement, transformant les nuances de couleur en une danse artistique qui invite à la contemplation.",
    ],
    [
        "id" => 14,
        "img" => "steve-johnson-4.png",
        "alt" => "Mirage",
        "titre" => "MIRAGE",
        "auteur" => "Stéphanie Kaiser",
        "description" => " Stéphanie Kaiser a réussi avec cette œuvre à créer une atmosphère éthérée et mystérieuse. À travers des formes abstraites et jouant avec les couleurs complémentaires, elle explore le thème du mirage, invitant le spectateur à questionner la réalité et la perception. Les nuances vibrantes et la composition dynamique suggèrent une réflexion sur les illusions visuelles et les ambiguïtés de l'existence.",
    ],
    [
        "id" => 15,
        "img" => "steve-johnson-3.png",
        "alt" => "Blaue Gelbe Muster",
        "titre" => "BLAUE GELBE MUSTER",
        "auteur" => "Adelheid Von Schreiber",
        "description" => "Adelheid Von Schreiber capture l'éclat et la profondeur des couleurs sous-marines. Il réussi à nous transmettre la joie effervescente et l'énergie vibrante de la vie aquatique.",
    ],

];
